[package]
name = "heehawbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "stream"] }
serenity = { version = "0.12", features = [
    "client",
    "standard_framework",
    "voice",
    "cache",
] }
songbird = { version = "0.4.0", default-features = true }
tokio = { version = "1.0", features = ["full"] }
